### ISSUE TITLE
PSVita broken call menu

### ISSUE THREAD

**Issue by pnavfrost** [ShrineFox/Persona-4-Golden-Mod-Menu#19]
Hi, I know this is for the PC version but I'm new to github and didn't find the Issues page there, so I'm writing this here
Basically the gist of it is that I... can't go over the second page of numbers in any number-related call menu (like Yen or Items), I can only select 0-4 numbers but I can't change the pages with the DPad, like I can with other menus (like the Date one, since it makes you choose Month first and its in letters, but again, can't go to 5-9 numbers)
Again, this only happens with the Vita version, using the 1.14 version of the Mod Menu on the fork there, on a 3.60 enso Vita.
Thanks in advance!

**Comment by ShrineFox** [comment]
Thanks for the report, this should now be fixed across all versions
